---
- name: Add repository for node 11
  shell: curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
  become: yes

- name: Install latest package
  become: yes
  apt:
    name: nodejs
    state: latest
    update_cache: yes
    force: yes

- name: Deleting the existing repo directory
  file: 
    path: "{{itrust_directory}}"
    state: absent

- name: Creating a local directory for itrust
  file: 
    path: "{{itrust_directory}}"
    state: directory
    mode: 0775

- name: Cloning the lastest itrust repo
  git:
    repo: 'git@github.ncsu.edu:sbajaj/iTrust2-v4.git'
    dest: "{{itrust_directory}}"

- name: Adding pre-push hook
  template:
    src: "pre-push-hook"
    dest: "{{itrust_directory}}/.git/hooks/pre-push"
    mode: 0767
  

- name: Adding the fuzzer.js file
  template:
    src: "fuzzer.js"
    dest: "{{itrust_directory}}/fuzzer.js"
    mode: 0666

- name: Adding package.json file for fuzzer.js
  template: 
    src: "package.json"
    dest: "{{itrust_directory}}/package.json"
    
- name: Setting up git config on localhost
  shell: "git config --global user.name \"Fuzzer\" && git config --global user.email \"Fuzzer\"" 

- name: Git add and checkout to master
  shell: "cd {{itrust_directory}} && npm install && git checkout master && touch fuzzer.js && git add . && git commit -m \"Starting the fuzzing task\""

- name: Pushing to itrust to trigger fuzzing for 100 iterations
  shell: "cd {{itrust_directory}} && git push -u origin master 



