---
- name: Add repository for node 11
  shell: curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
  become: yes

- name: Install latest package
  become: yes
  apt:
    name: nodejs
    state: latest
    update_cache: yes
    force: yes

- name: DELETE iTrustClone dirctory if it exists
  file: 
    path: "{{itrust_directory}}"
    state: absent

- name: CREATE iTrustClone directory
  file: 
    path: "{{itrust_directory}}"
    state: directory
    mode: 0775

- name: Git Clone
  git:
    repo: 'git@github.ncsu.edu:sbajaj/iTrust2-v4.git'
    dest: "{{itrust_directory}}"

- name: Add Pre-Push Hook
  template:
    src: "pre-push-hook"
    dest: "{{itrust_directory}}/.git/hooks/pre-push"
    mode: 0767
  

- name: Add Fuzzer.js file
  template:
    src: "fuzzer.js"
    dest: "{{itrust_directory}}/fuzzer.js"
    mode: 0666

- name: adding package.json file for fuzzer.js
  template: 
    src: "package.json"
    dest: "{{itrust_directory}}/package.json"


- name: Git add and checkout to master
  shell: "cd {{itrust_directory}} && npm install && git checkout master && touch fuzzer.js && git add . && git commit -m \"Commiting to master by developer\" && git push"



