---
- name: Enable sudo access to jenkins user 
  lineinfile:
    path: /etc/sudoers
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  become: true

- name: Setup mongoDb for checkboxio
  copy:
    src: "templates/setup_mongodb.yml"
    dest: /var/lib/jenkins/setup_mongodb.yml
    owner: jenkins
    group: jenkins
    mode: 0666
  become: yes

#- name: Copy checkbox job script
#  template:
#    src: "checkbox_jenkins_jobs.yml"
#    dest: /home/vagrant/jobs/checkbox_jenkins_jobs.yml
#  become: yes

- name: Copy Checkbox.io Deployment jenkins job script
  template:
    src: "checkbox_jenkins_jobs.yml"
    dest: /home/ubuntu/jobs/{{checkbox_job}}.yml
  become: yes


- name: Put the script on server for build job
  template:
   src:  "iTrust_jenkins_jobs.yml"
   dest: /home/ubuntu/jobs/{{iTrust_job}}.yml
  become: yes
- name: read admin pwd | Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: adminpwd
  become: true

- name: check if itrust git folder exists
  stat:
    path: "/var/lib/jenkins/workspace/{{ iTrust_job }}/iTrust2-v4/"
  register: gitexists

- name: delete if the itrust directory exists
  file:
    state: absent
    path: "/var/lib/jenkins/workspace/{{ iTrust_job }}/iTrust2-v4"
  when: gitexists.stat.exists
  become: true

- name: removing password authentication for maven
  lineinfile:
    path: /etc/sudoers
    line: "jenkins ALL=(ALL) NOPASSWD: ALL"
  become: true

- jenkins_script:
   script: |
    import jenkins.model.*
    import hudson.security.*
    def instance = Jenkins.getInstance()
    instance.disableSecurity()
    instance.save()
   user: admin
   password: "{{ adminpwd.stdout }}"

- name: Change Jenkins port
  replace:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT=8080'
    replace: 'HTTP_PORT=9000'
  become: true

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
  become: true

- name: Delay added
  wait_for: 
    port: 9000 
    delay: 10

- name: create jobs
  shell: 'jenkins-jobs --conf /home/ubuntu/jenkins_jobs.ini update /home/ubuntu/jobs'



# - jenkins_script:
#    script: |
#     import jenkins.model.*
#     import hudson.security.*
#     def sinstance = Jenkins.getInstance()
#     def hudsonRealm = new HudsonPrivateSecurityRealm(false)
#     instance.setSecurityRealm(hudsonRealm)
#     def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
#     strategy.setAllowAnonymousRead(false)
#     instance.setAuthorizationStrategy(strategy)
#     instance.save()
#    user: admin
#    password: "{{ adminpwd.stdout }}"
