- job:
    name: "{{job_name}}"
    scm: 
      - git: 
          url: https://github.com/alagava/checkbox.io.git
          branches: 
            - origin/master
          wipe-workspace: false
    triggers:
      - github:
    builders:
      - shell: 'sudo git clone https://github.com/chrisparnin/checkbox.io.git'
      - shell: 'cd /var/lib/jenkins/workspace/{{job_name}}/checkbox.io/server-side/site && sudo npm install'

